[colors.bright]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#2d353b"
foreground = "#d3c6aa"

[cursor.style]
blinking = "Always"
shape = "Beam"

# [everforest_dark_medium.bright]
# black = "#475258"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
#
# [everforest_dark_medium.normal]
# black = "#475258"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
#
# [everforest_dark_medium.primary]
# background = "#2d353b"
# foreground = "#d3c6aa"

[font]
size = 10.0

[font.normal]
# family = "Myfonts"
family = "ConsolaMono"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C\""
key = "V"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C%"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C|"
key = "Return"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cc"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001CC"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cx"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C&"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cd"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C[/"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ch"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Cj"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Ck"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Cl"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001CH"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CJ"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CK"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CL"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CH"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CJ"
key = "Down"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CK"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001CL"
key = "Right"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cp"
key = "Tab"
mods = "Control"

[scrolling]
history = 10000

[shell]
# args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "none"
opacity = 0.6
startup_mode = "Maximized"
