version: "2"
run:
  concurrency: 4
  go: "1.24"
  issues-exit-code: 1
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - gosmopolitan
    - varnamelen
    - err113
    - exhaustruct
    - wrapcheck
    - mnd
    - tagliatelle
    - wsl
    - gochecknoglobals
  settings:
    bidichk:
      left-to-right-embedding: true
      right-to-left-embedding: true
      pop-directional-formatting: true
      left-to-right-override: true
      right-to-left-override: true
      left-to-right-isolate: true
      right-to-left-isolate: true
      first-strong-isolate: true
      pop-directional-isolate: true
    cyclop:
      max-complexity: 50
      package-average: 0
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: false
      check-blank: false
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    exhaustive:
      default-signifies-exhaustive: false
      ignore-enum-members: ""
      package-scope-only: false
    forbidigo:
      forbid:
        - pattern: ^print.*$
        - pattern: fmt\.Print.*
        - pattern: fmt.Println.*
        - pattern: ginkgo\\.F.*
    funlen:
      lines: 250
      statements: 80
    gocognit:
      min-complexity: 40
    goconst:
      match-constant: true
      min-len: 3
      min-occurrences: 3
      numbers: false
      min: 3
      max: 3
      ignore-calls: true
    gocritic:
      enabled-checks:
        - ruleguard
      disabled-checks:
        - regexpMust
        - ifElseChain
      enabled-tags:
        - performance
      disabled-tags:
        - experimental
      settings:
        captLocal:
          paramsOnly: true
        elseif:
          skipBalanced: true
        hugeParam:
          sizeThreshold: 80
        nestingReduce:
          bodyWidth: 5
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        rangeValCopy:
          sizeThreshold: 32
          skipTestFuncs: true
        ruleguard:
          rules: ""
        truncateCmp:
          skipArchDependent: true
        underef:
          skipRecvDeref: true
        unnamedResult:
          checkExported: true
    gocyclo:
      min-complexity: 30
    godot:
      scope: declarations
      capital: false
    godox:
      keywords:
        - BUG
        - FIXME
        - OPTIMIZE
        - HACK
    gomoddirectives:
      replace-allow-list:
        - google.golang.org/grpc
        - github.com/marmotedu/api
        - github.com/marmotedu/component-base
        - github.com/marmotedu/marmotedu-sdk-go
      replace-local: true
      exclude-forbidden: false
      retract-allow-no-explanation: false
    gosec:
      includes:
        - G306
        - G101
      excludes:
        - G204
      severity: low
      confidence: low
      config:
        G101:
          entropy_threshold: "80.0"
          ignore_entropy: false
          pattern: (?i)example
          per_char_threshold: "3.0"
          truncate: "32"
        G306: "0600"
    govet:
      enable:
        - atomicalign
      disable:
        - shadow
      enable-all: false
      disable-all: false
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - (or|er)$
    lll:
      line-length: 240
      tab-width: 4
    makezero:
      always: false
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 7
    nilnil:
      checked-types:
        - ptr
        - func
        - iface
        - map
        - chan
    nolintlint:
      require-explanation: false
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    predeclared:
      qualified-name: false
    promlinter:
      strict: false
    revive:
      max-open-files: 2048
      confidence: 0.7
      severity: warning
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.
              allowInts: 0,1,2
              allowStrs: '""'
              maxLitCount: "3"
          severity: warning
          disabled: true
        - name: argument-limit
          arguments:
            - 4
          severity: warning
          disabled: false
        - name: atomic
          severity: warning
          disabled: false
        - name: banned-characters
          arguments:
            - Ω
            - Σ
            - σ
          severity: warning
          disabled: false
        - name: bare-return
          severity: warning
          disabled: false
        - name: blank-imports
          severity: warning
          disabled: false
        - name: bool-literal-in-expr
          severity: warning
          disabled: false
        - name: call-to-gc
          severity: warning
          disabled: false
        - name: cognitive-complexity
          arguments:
            - 7
          severity: warning
          disabled: true
        - name: comment-spacings
          arguments:
            - mypragma
            - otherpragma
          severity: warning
          disabled: false
        - name: confusing-naming
          severity: warning
          disabled: true
        - name: confusing-results
          severity: warning
          disabled: false
        - name: constant-logical-expr
          severity: warning
          disabled: false
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T,*github.com/user/repo/testing.Harness'
          severity: warning
          disabled: true
        - name: context-keys-type
          severity: warning
          disabled: false
        - name: cyclomatic
          arguments:
            - 3
          severity: warning
          disabled: true
        - name: datarace
          severity: warning
          disabled: false
        - name: deep-exit
          severity: warning
          disabled: false
        - name: defer
          arguments:
            - - call-chain
              - loop
          severity: warning
          disabled: false
        - name: dot-imports
          severity: warning
          disabled: false
        - name: duplicated-imports
          severity: warning
          disabled: false
        - name: early-return
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: empty-block
          severity: warning
          disabled: false
        - name: empty-lines
          severity: warning
          disabled: false
        - name: enforce-map-style
          arguments:
            - make
          severity: warning
          disabled: false
        - name: error-naming
          severity: warning
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
        - name: error-strings
          severity: warning
          disabled: false
        - name: errorf
          severity: warning
          disabled: false
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
          severity: warning
          disabled: false
        - name: file-header
          arguments:
            - This is the text that must appear at the top of source files.
          severity: warning
          disabled: true
        - name: flag-parameter
          severity: warning
          disabled: true
        - name: function-result-limit
          arguments:
            - 3
          severity: warning
          disabled: false
        - name: function-length
          arguments:
            - 20
            - 5
          severity: warning
          disabled: true
        - name: get-return
          severity: warning
          disabled: true
        - name: identical-branches
          severity: warning
          disabled: false
        - name: if-return
          severity: warning
          disabled: false
        - name: increment-decrement
          severity: warning
          disabled: false
        - name: indent-error-flow
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: import-alias-naming
          arguments:
            - ^[a-z][a-z0-9]{0,}$
          severity: warning
          disabled: true
        - name: import-shadowing
          severity: warning
          disabled: true
        - name: line-length-limit
          arguments:
            - 240
          severity: warning
          disabled: false
        - name: max-public-structs
          arguments:
            - 3
          severity: warning
          disabled: true
        - name: modifies-parameter
          severity: warning
          disabled: false
        - name: modifies-value-receiver
          severity: warning
          disabled: false
        - name: nested-structs
          severity: warning
          disabled: false
        - name: optimize-operands-order
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: true
        - name: range
          severity: warning
          disabled: false
        - name: range-val-in-closure
          severity: warning
          disabled: false
        - name: range-val-address
          severity: warning
          disabled: false
        - name: receiver-naming
          severity: warning
          disabled: true
        - name: redundant-import-alias
          severity: warning
          disabled: false
        - name: redefines-builtin-id
          severity: warning
          disabled: false
        - name: string-of-int
          severity: warning
          disabled: false
        - name: string-format
          arguments:
            - - core.WriteError[1].Message
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /(^|[^\.!?])$/
              - must not end in punctuation
            - - panic
              - /^[^\n]*$/
              - must not contain line breaks
          severity: warning
          disabled: true
        - name: struct-tag
          arguments:
            - json,inline
            - bson,outline,gnu
          severity: warning
          disabled: false
        - name: superfluous-else
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: time-equal
          severity: warning
          disabled: false
        - name: time-naming
          severity: warning
          disabled: false
        - name: var-naming
          arguments:
            - - ID
            - - VM
            - - upperCaseConst: true
          severity: warning
          disabled: true
        - name: var-declaration
          severity: warning
          disabled: false
        - name: unconditional-recursion
          severity: warning
          disabled: false
        - name: unexported-naming
          severity: warning
          disabled: true
        - name: unexported-return
          severity: warning
          disabled: true
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
          severity: warning
          disabled: false
        - name: unnecessary-stmt
          severity: warning
          disabled: false
        - name: unreachable-code
          severity: warning
          disabled: false
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
        - name: unused-receiver
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: true
        - name: useless-break
          severity: warning
          disabled: false
        - name: waitgroup-by-value
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - all
      initialisms:
        - ACL
        - API
        - ASCII
        - CPU
        - CSS
        - DNS
        - EOF
        - GUID
        - HTML
        - HTTP
        - HTTPS
        - ID
        - IP
        - JSON
        - QPS
        - RAM
        - RPC
        - SLA
        - SMTP
        - SQL
        - SSH
        - TCP
        - TLS
        - TTL
        - UDP
        - UI
        - GID
        - UID
        - UUID
        - URI
        - URL
        - UTF8
        - VM
        - XML
        - XMPP
        - XSRF
        - XSS
        - SIP
        - RTP
        - AMQP
        - DB
        - TS
      dot-import-whitelist:
        - fmt
      http-status-code-whitelist:
        - "200"
        - "400"
        - "404"
        - "500"
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          json: camel
          mapstructure: kebab
          xml: camel
          yaml: camel
        use-field-name: true
    testpackage:
      skip-regexp: (id|export|internal)_test\.go
    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: true
    unparam:
      check-exported: true
    whitespace:
      multi-if: false
      multi-func: false
    wsl:
      strict-append: true
      allow-assign-and-call: true
      allow-assign-and-anything: false
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: false
      allow-separated-leading-comment: false
      allow-cuddle-declarations: false
      force-err-cuddling: false
  exclusions:
    generated: lax
    paths:
      - .*\.my\.go$
      - _test.go
      - _handler.go
      - _gen.go
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
severity:
  default: info
  rules:
    - linters:
        - dupl
      severity: info
# formatters:
#   enable:
#     - gofmt
#     - gofumpt
#     - goimports
#   settings:
#     gofmt:
#       simplify: true
#     gofumpt:
#       extra-rules: false
#   exclusions:
#     generated: lax
#     paths:
#       - .*\.my\.go$
#       - _test.go
#       - _handler.go
#       - _gen.go
#       - third_party$
#       - builtin$
#       - examples$
