vsync = true
# frame = "transparent"
no-multigrid = false
maximized = false
srgb = true
idle = true

[font]
# normal = { family = "Monaspace Radon", style = "W100"}
# normal = { family = "CodeNewRoman Nerd Font Mono", style = "W100"}
# normal = { family = "ComicShannsMono Nerd Font Mono", style = "W100"}
# normal = { family = "UbuntuSansMono Nerd Font Mono", style = "W300"}

size = 13
# features = { "Monaspace Radon" = ["+ss01", "+ss02","+ss03","+ss04","+ss05","+ss06","+ss07", "+ss08", "+dlig"] }
features = { "Comic Code" = ["+ss01", "+ss02","+ss03","+ss04","+ss05","+ss06","+ss07", "+ss08", "+dlig"] }
# width = 1.3
width = 1.2
[[font.normal]]
# family =  "Comic Code"
style = "Italic"

family =  "Binchotan_Sharp"
[[font.normal]]
family =  "CodeNewRoman Nerd Font"
style = "W100"
